"""empty message

Revision ID: 011031e1d7d6
Revises: 
Create Date: 2023-04-15 19:29:49.072619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011031e1d7d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
