"""empty message

Revision ID: 3535bc49728e
Revises: 011031e1d7d6
Create Date: 2023-04-15 20:19:24.158451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3535bc49728e'
down_revision = '011031e1d7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###
