"""empty message

Revision ID: fd84b378bccd
Revises: 3535bc49728e
Create Date: 2023-04-15 21:30:38.396870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd84b378bccd'
down_revision = '3535bc49728e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
